In [1]:
import torch

In [2]:
x = torch.randn((2,3,4))

In [3]:
x.shape

torch.Size([2, 3, 4])

In [8]:
x

tensor([[[-0.0340, -1.6216,  1.8247, -0.0461],
         [ 0.3277,  1.1541,  0.1000, -0.7303],
         [-1.2196,  1.2407,  0.8018,  0.0052]],

        [[-0.2023, -1.7310,  0.3731, -0.9301],
         [ 0.2443,  1.0060, -0.4614,  0.7006],
         [ 0.4452, -0.2359,  1.4386, -1.8760]]])

In [15]:
max_x = torch.max(x, dim=2, keepdim=True).values

In [17]:
max_x.shape

torch.Size([2, 3, 1])

In [19]:
x = x - max_x

In [22]:
torch.exp(x).shape

torch.Size([2, 3, 4])

In [23]:
torch.sum(torch.exp(x), dim=2, keepdim=True)

tensor([[[1.3417],
         [1.9381],
         [2.0208]],

        [[1.9561],
         [2.4342],
         [1.5941]]])

In [24]:
softmax_x = torch.exp(x) / torch.sum(torch.exp(x), dim=2, keepdim=True)

In [25]:
softmax_x

tensor([[[0.1162, 0.0237, 0.7453, 0.1148],
         [0.2258, 0.5160, 0.1798, 0.0784],
         [0.0423, 0.4948, 0.3190, 0.1438]],

        [[0.2875, 0.0623, 0.5112, 0.1389],
         [0.1918, 0.4108, 0.0947, 0.3027],
         [0.2323, 0.1176, 0.6273, 0.0228]]])

In [26]:
torch.sum(softmax_x, dim=-1)

tensor([[1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000]])